[project]
channels = ["pytorch", "conda-forge"]
description = "Add a short description here"
name = "sam"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cpuonly = "*"
imageio = ">=2.11.0,<2.28.0"
nifty = { version = ">=1.2.1,<2", build = "*_4" }
imagecodecs = "*"
magicgui = "*"
napari = ">=0.5.0"
natsort = "*"
pip = "*"
pooch = "*"
protobuf = "<5"
pyqt = "*"
python-xxhash = "*"
python-elf = ">=0.4.8"
pytorch = ">=2.4"
segment-anything = "*"
torchvision = "*"
torch_em = ">=0.7.0"
tqdm = "*"
timm = "*"
zarr = "<2.18.0"

[pypi-dependencies]
bioio = "==1.1.0"
mobile-sam = { git = "https://github.com/ChaoningZhang/MobileSAM.git" }
micro-sam = { git = "https://github.com/tim-hudelmaier/micro-sam.git" }
bioio-ome-tiff = ">=1.0.1, <2"
bioio-lif = "*"
einops = ">=0.8.0, <0.9"
loguru = "*"
fire = ">=0.7.0, <0.8"

[tool.pixi.dependencies]
python = "3.11.*"
